# Generated by Django 4.0.1 on 2023-01-25 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='city',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AddField(
            model_name='station',
            name='image',
            field=models.CharField(default='', max_length=255),
        ),
    ]
