# Generated by Django 4.0.1 on 2023-01-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_station_city_station_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='city',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='station',
            name='image',
            field=models.CharField(max_length=255),
        ),
    ]
