# Generated by Django 4.0.1 on 2023-01-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0004_rename_state_station_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='type',
            field=models.CharField(default='a', max_length=60),
            preserve_default=False,
        ),
    ]
