# Generated by Django 4.0.1 on 2023-01-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0005_station_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='id_station',
            field=models.CharField(blank=True, max_length=15, primary_key=True, serialize=False, unique=True),
        ),
    ]
