# Generated by Django 4.0.1 on 2023-01-30 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0006_alter_station_id_station'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id_slot', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('state', models.BooleanField(default=True)),
                ('id_station', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stations.station')),
            ],
        ),
    ]
