# Generated by Django 4.0.1 on 2023-02-15 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0002_slot_bike'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slot',
            old_name='state',
            new_name='status',
        ),
    ]
