# Generated by Django 4.0.1 on 2023-02-19 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id_notification', models.CharField(blank=True, max_length=15, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=40)),
                ('body', models.CharField(max_length=255)),
                ('send_date', models.CharField(max_length=255)),
                ('read', models.BooleanField(default=1)),
                ('from_user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='from_user_id', to='users.user')),
                ('to_user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_user_id', to='users.user')),
            ],
        ),
    ]
