# Generated by Django 4.0.1 on 2023-02-02 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bikes', '0002_alter_bike_id_slot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id_rent', models.CharField(blank=True, max_length=15, primary_key=True, serialize=False, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True)),
                ('id_bike', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bikes.bike')),
            ],
        ),
    ]
