# Generated by Django 4.0.1 on 2023-02-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rents', '0002_rename_id_bike_rent_bike_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
