# Generated by Django 4.0.1 on 2023-02-02 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0001_initial'),
        ('bikes', '0002_alter_bike_id_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='id_slot',
        ),
        migrations.AddField(
            model_name='bike',
            name='slot',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='slots.slot'),
        ),
    ]
