# Generated by Django 4.0.1 on 2023-02-02 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0003_remove_bike_id_slot_bike_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='slot',
        ),
    ]
